server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 10M;

    location /api/notifications/subscribe {
        proxy_pass http://backend:8080/notifications/subscribe;
        proxy_set_header Host $host;
        proxy_http_version 1.1;
        proxy_set_header Connection '';
        proxy_buffering off;
        proxy_cache off;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}